spring:
  boot:
    message: Hello, department service updated and refreshed
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/






